#
# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /authenticate:
    post:
      description: Authenticate a login
      requestBody:
        description: Login details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionToken'
        401:
          description: Username or password incorrect
          content:
            application/json:
              schema:
                type: string
  /newuser:
    post:
      description: Create a new user
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        200:
          description: User created
        409:
          description: User already exists
  /listings:
    get:
      description: Get listed items
      parameters:
        - name: category
          in: query
          description: Category of items
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingList'
        400:
          description: Invalid search value
        404:
          description: No items found
  /listing:
    get:
      description: Get a specific listing
      parameters:
        - name: id
          in: query
          description: Item id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingFull'
        404:
          description: Item not found
    # Unfinished
    # post:
    #   description: Post a new item
    #   requestBody:
    #     description: Item to post
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Item'
    #   responses:
    #     201:
    #       description: Item successfully listed
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Item'
    #     401:
    #       description: Unauthorized
    #     409:
    #       description: Item already listed
  /category:
    get:
      description: Get a category
      parameters:
        - name: category
          in: query
          description: category id
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Got Category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        404:
          description: Category not found

  /category:
    get:
      description: Get a category
      parameters:
        - name: category
          in: query
          description: category id
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Got Category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        404:
          description: Category not found

components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    DummyResponse:
      properties:
        message:
          type: string
      required:
        - message

    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        id:
          type: string
          format: uuid
      required:
        - name
        - email
        - id
      additionalProperties: false

    NewUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - name
        - email
        - password
      additionalProperties: false

    LoginUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
      additionalProperties: false

    SessionToken:
      type: object
      properties:
        owner:
          $ref: '#/components/schemas/User'
        accessToken:
          type: string

    CategoryResponse:
      type: object
      properties:
        category:
          $ref: '#/components/schemas/Category'
        subcategories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        filters:
          type: array
          items:
            type: string
            pattern: '^\w+$'
      required:
        - category
      additionalProperties: false

    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    Listing:
      type: object
      properties:
        category:
          $ref: '#/components/schemas/Category'
        owner:
          $ref: '#/components/schemas/User'
        attributes:
          type: object
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: string
          pattern: '^\$?(?:\d+)?(?:.\d{2})?$'
        image:
          type: string
      required:
        - category
        - owner
        - attributes
        - id
        - name
        - price
      additionalProperties: false

    ListingFull:
      type: object
      properties:
        category:
          $ref: '#/components/schemas/Category'
        owner:
          $ref: '#/components/schemas/User'
        attributes:
          type: object
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: string
          pattern: '^\$?(?:\d+)?(?:.\d{2})?$'
        description:
          type: string
        images:
          type: array
          items:
            type: string
      required:
        - category
        - owner
        - attributes
        - id
        - name
        - price
        - description
      additionalProperties: false

    ListingList:
      type: array
      items:
        $ref: '#/components/schemas/Listing'

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
