#
# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    DummyResponse:
      properties:
        message:
          type: string
      required:
        - message

    User:
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        id:
          type: string
          format: uuid
      required:
        - id

    Item:
      properties:
        category:
          type: string
        subcategory:
          type: string
        name:
          type: string
        owner:
          $ref: '#/components/schemas/User'
        price:
          type: string
          pattern: '^\$?\d+(?:.\d{2})?$'
        description:
          type: string
        location:
          type: string
          # location will be changed when we get to the stretch part
      required:
        - owner
        - name
        - category

    ItemList:
      properties:
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
  - bearerAuth: []         # use the same name as above
